# Generated by Django 4.2.7 on 2023-11-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_rename_collegename_contact_schoolname"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="sslc",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
