# Generated by Django 4.2.7 on 2023-11-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_rename_hscshoolname_contact_hscschoolname"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="hscpercentile",
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="JeeAppNo",
            field=models.CharField(max_length=109),
        ),
        migrations.AlterField(
            model_name="contact",
            name="Percentage",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="contact",
            name="hscpercentile",
            field=models.CharField(max_length=60),
        ),
    ]
