# Generated by Django 4.2.7 on 2023-11-25 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_remove_contact_jeeappno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="hscpercentile",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="hscschoolname",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="hscpercentile",
        ),
    ]
