# Generated by Django 4.2.7 on 2023-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="hscmark",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
