# Generated by Django 4.2.7 on 2023-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_course_hscmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="hscmark",
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="hscschool",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
