# Generated by Django 4.2.7 on 2023-11-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_alter_course_studentname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="studentname",
            field=models.CharField(max_length=122),
        ),
    ]
