# Generated by Django 4.2.7 on 2023-11-27 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_alter_course_studentname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="studentname",
            new_name="applicantname",
        ),
    ]
