# Generated by Django 4.2.7 on 2023-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_remove_student_name_student_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="applicantname",
        ),
        migrations.AddField(
            model_name="course",
            name="studentname",
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
