# Generated by Django 4.2.7 on 2023-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0034_remove_course_applicantname_course_studentname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="studentname",
            field=models.CharField(default="", max_length=122),
        ),
    ]
