# Generated by Django 4.2.7 on 2023-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_rename_studentname_course_studentname"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="group",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
