# Generated by Django 4.2.7 on 2023-11-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0041_delete_yourmodel_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(default="", max_length=12),
        ),
    ]
