# Generated by Django 4.2.7 on 2023-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0042_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="studentname",
            field=models.CharField(max_length=122),
        ),
    ]
