# Generated by Django 4.2.8 on 2023-12-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0043_alter_course_studentname"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course",
            field=models.CharField(
                choices=[
                    ("html_css", "HTML and CSS Basics"),
                    ("javascript", "JavaScript Fundamentals"),
                    ("python", "Python for Beginners"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
