# Generated by Django 4.2.8 on 2023-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0044_course_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course",
        ),
        migrations.AddField(
            model_name="course",
            name="selected_course",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
