# Generated by Django 4.2.8 on 2023-12-06 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0046_rename_selected_course_course_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="hscmark",
            new_name="hscpercentage",
        ),
    ]
