# Generated by Django 4.2.8 on 2023-12-06 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0047_rename_hscmark_course_hscpercentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="hscpercentage",
        ),
    ]
