# Generated by Django 4.2.8 on 2023-12-06 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0048_remove_course_hscpercentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="group",
            new_name="hscpercentage",
        ),
    ]
