# Generated by Django 4.2.8 on 2023-12-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0049_rename_group_course_hscpercentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Username",
            field=models.CharField(max_length=15),
        ),
    ]
