# Generated by Django 4.2.8 on 2023-12-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0053_ranklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="rank",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
