# Generated by Django 4.2.8 on 2023-12-10 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0054_student_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="rank",
        ),
    ]
