# Generated by Django 4.2.8 on 2023-12-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0055_remove_student_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="studentname",
            field=models.CharField(max_length=19, null=True),
        ),
    ]
