# Generated by Django 4.2.8 on 2023-12-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0056_alter_course_studentname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="studentname",
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
