# Generated by Django 4.2.8 on 2023-12-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0058_remove_contact_schoolname_remove_contact_sslc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="marksheet",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
