# Generated by Django 4.2.8 on 2023-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0059_student_marksheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="marksheet",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
