# Generated by Django 4.2.8 on 2023-12-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0060_alter_student_marksheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
