# Generated by Django 4.2.8 on 2023-12-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0061_contact_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="religion",
            field=models.CharField(
                choices=[
                    ("christianity", "Christianity"),
                    ("islam", "Islam"),
                    ("hinduism", "Hinduism"),
                    ("buddhism", "Buddhism"),
                    ("other", "Other"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=9
            ),
        ),
    ]
