# Generated by Django 4.2.8 on 2023-12-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0062_contact_religion_alter_contact_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ugpercentage",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
