# Generated by Django 4.2.8 on 2023-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0064_alter_course_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="ugpercentage",
            field=models.FloatField(null=True),
        ),
    ]
