# Generated by Django 4.2.8 on 2023-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0065_alter_course_ugpercentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="ugpercentage",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
