# Generated by Django 4.2.7 on 2023-11-23 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_contact_hscpercentile_contact_hscshoolname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="hscshoolName",
            new_name="hscschoolname",
        ),
    ]
