# Generated by Django 4.2.7 on 2023-11-25 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_destination_hscpercentile_alter_contact_jeeappno_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="JeeAppNo",
        ),
    ]
