# Generated by Django 4.2.7 on 2023-11-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_remove_contact_hscpercentile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="hscpercentile",
            field=models.IntegerField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="hscschoolname",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="hscpercentile",
            field=models.IntegerField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
