# Generated by Django 4.2.7 on 2023-11-26 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_alter_contact_hscpercentile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="Percentage",
        ),
    ]
