# Generated by Django 4.2.7 on 2023-11-26 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_remove_contact_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="hscpercentile",
        ),
    ]
