# Generated by Django 4.2.7 on 2023-11-26 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_remove_contact_hscpercentile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="hscschoolname",
        ),
    ]
