# Generated by Django 4.2.7 on 2023-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_remove_contact_hscschoolname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coursename", models.CharField(max_length=122)),
            ],
        ),
    ]
