# Generated by Django 4.2.7 on 2023-11-26 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="coursename",
            new_name="studentname",
        ),
    ]
