# Generated by Django 4.2.7 on 2023-11-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_student_hscmark_student_hscschool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="hscmark",
            field=models.IntegerField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="student",
            name="hscschool",
            field=models.CharField(default="", max_length=100),
        ),
    ]
