# Generated by Django 4.2.7 on 2023-11-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_rename_studentname_course_applicantname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.AddField(
            model_name="student",
            name="Username",
            field=models.CharField(default=" ", max_length=15),
        ),
    ]
