# Generated by Django 4.2.7 on 2023-11-28 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_alter_student_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="studentname",
            new_name="Studentname",
        ),
    ]
