# Generated by Django 4.2.7 on 2023-11-30 14:12

import django.core.validators
from django.db import migrations, models
import home.views


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_course_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number can only contain digits.",
                        regex="^[0-9]+$",
                    )
                ],
            ),
        ),
    ]
