# Generated by Django 4.2.8 on 2023-12-06 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0045_remove_course_course_course_selected_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="selected_course",
            new_name="course",
        ),
    ]
