# Generated by Django 4.2.8 on 2023-12-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0057_alter_course_studentname"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="pgcourse",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
