# Generated by Django 4.2.8 on 2023-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0058_course_pgcourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="studentname",
            field=models.CharField(max_length=122, null=True),
        ),
    ]
