# Generated by Django 4.2.8 on 2023-12-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0059_alter_course_course_alter_course_studentname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course",
        ),
        migrations.RemoveField(
            model_name="course",
            name="pgcourse",
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
