# Generated by Django 4.2.8 on 2023-12-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0061_course_ugmark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="ugmark",
        ),
        migrations.AddField(
            model_name="course",
            name="selected_course",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(choices=[("ug", "UG"), ("pg", "PG")], max_length=2),
        ),
    ]
