# Generated by Django 4.2.8 on 2023-12-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0062_remove_course_ugmark_course_selected_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
