# Generated by Django 4.2.8 on 2023-12-12 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0063_course_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RankList",
        ),
    ]
