# Generated by Django 4.2.8 on 2023-12-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0064_delete_ranklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="hscmark",
            field=models.FloatField(default="", max_length=3),
        ),
    ]
